-- Supabase DDL SQL Schema for Accountability Dashboard
-- Copy and run this script in your Supabase SQL Editor (https://supabase.com)

-- 1. DAILY HISTORY TABLE
-- Stores daily aggregated statistics, habits, notes, and scores
CREATE TABLE IF NOT EXISTS public.daily_history (
    user_id TEXT DEFAULT 'default' NOT NULL,
    date DATE NOT NULL,
    score INTEGER DEFAULT 0 NOT NULL,
    work_minutes INTEGER DEFAULT 0 NOT NULL,
    wasted_minutes INTEGER DEFAULT 0 NOT NULL,
    habits JSONB DEFAULT '{}'::jsonb NOT NULL,
    schedule_completion NUMERIC(5, 2) DEFAULT 0.00 NOT NULL,
    notes TEXT,
    energy_logs JSONB DEFAULT '[]'::jsonb,
    sleep_data JSONB,
    sessions JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (user_id, date)
);

-- 2. TIMER SESSIONS TABLE
-- Stores detail records for each focus block session recorded by the timer
CREATE TABLE IF NOT EXISTS public.timer_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT DEFAULT 'default' NOT NULL,
    date DATE NOT NULL,
    project TEXT DEFAULT 'Untagged' NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes NUMERIC(6, 2) DEFAULT 0.00 NOT NULL,
    gaps JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on tables
ALTER TABLE public.daily_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timer_sessions ENABLE ROW LEVEL SECURITY;

-- Create basic policies to allow anyone with API keys (anon) to perform CRUD
-- In a multi-user app, you would bind these to auth.uid()
CREATE POLICY "Enable all access for daily_history" 
    ON public.daily_history FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Enable all access for timer_sessions" 
    ON public.timer_sessions FOR ALL 
    USING (true) 
    WITH CHECK (true);

--Create indices for performant historical queries
CREATE INDEX IF NOT EXISTS idx_daily_history_date ON public.daily_history(date DESC);
CREATE INDEX IF NOT EXISTS idx_timer_sessions_date ON public.timer_sessions(date DESC);
CREATE INDEX IF NOT EXISTS idx_timer_sessions_project ON public.timer_sessions(project);

-- 3. USER SETTINGS TABLE
-- Stores user configurations, profile settings, schedule templates, reminders, and timer preferences
CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id TEXT DEFAULT 'default' NOT NULL PRIMARY KEY,
    settings JSONB DEFAULT '{}'::jsonb NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on user_settings
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all access
CREATE POLICY "Enable all access for user_settings" 
    ON public.user_settings FOR ALL 
    USING (true) 
    WITH CHECK (true);

